package com.svea.webpayadminservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2024-04-29T16:22:46.075+02:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IAdminService")
@XmlSeeAlso({ObjectFactory.class})
public interface IAdminService {

    @WebMethod(operationName = "DeliverPartial", action = "http://tempuri.org/IAdminService/DeliverPartial")
    @Action(input = "http://tempuri.org/IAdminService/DeliverPartial", output = "http://tempuri.org/IAdminService/DeliverPartialResponse")
    @RequestWrapper(localName = "DeliverPartial", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.DeliverPartial")
    @ResponseWrapper(localName = "DeliverPartialResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.DeliverPartialResponse")
    @WebResult(name = "DeliverPartialResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.DeliveryResponse deliverPartial(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.PartialDeliveryRequest request
    );

    @WebMethod(operationName = "GetPaymentPlanReport", action = "http://tempuri.org/IAdminService/GetPaymentPlanReport")
    @Action(input = "http://tempuri.org/IAdminService/GetPaymentPlanReport", output = "http://tempuri.org/IAdminService/GetPaymentPlanReportResponse")
    @RequestWrapper(localName = "GetPaymentPlanReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetPaymentPlanReport")
    @ResponseWrapper(localName = "GetPaymentPlanReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetPaymentPlanReportResponse2")
    @WebResult(name = "GetPaymentPlanReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetPaymentPlanReportResponse getPaymentPlanReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetPaymentPlanReportRequest request
    );

    @WebMethod(operationName = "GetOrders", action = "http://tempuri.org/IAdminService/GetOrders")
    @Action(input = "http://tempuri.org/IAdminService/GetOrders", output = "http://tempuri.org/IAdminService/GetOrdersResponse")
    @RequestWrapper(localName = "GetOrders", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetOrders")
    @ResponseWrapper(localName = "GetOrdersResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetOrdersResponse2")
    @WebResult(name = "GetOrdersResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetOrdersResponse getOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetOrdersRequest request
    );

    @WebMethod(operationName = "GetInvoicesPaidToClientForReport", action = "http://tempuri.org/IAdminService/GetInvoicesPaidToClientForReport")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicesPaidToClientForReport", output = "http://tempuri.org/IAdminService/GetInvoicesPaidToClientForReportResponse")
    @RequestWrapper(localName = "GetInvoicesPaidToClientForReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoicesPaidToClientForReport")
    @ResponseWrapper(localName = "GetInvoicesPaidToClientForReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoicesPaidToClientForReportResponse")
    @WebResult(name = "GetInvoicesPaidToClientForReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetInvoicesPaidToClientForReportResponse2 getInvoicesPaidToClientForReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetInvoicesPaidToClientForReportRequest request
    );

    @WebMethod(operationName = "GetSpecificationReport", action = "http://tempuri.org/IAdminService/GetSpecificationReport")
    @Action(input = "http://tempuri.org/IAdminService/GetSpecificationReport", output = "http://tempuri.org/IAdminService/GetSpecificationReportResponse")
    @RequestWrapper(localName = "GetSpecificationReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetSpecificationReport")
    @ResponseWrapper(localName = "GetSpecificationReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetSpecificationReportResponse")
    @WebResult(name = "GetSpecificationReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetSpecificationReportResponse2 getSpecificationReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetSpecificationReportRequest request
    );

    @WebMethod(operationName = "CreateApprovedOrder", action = "http://tempuri.org/IAdminService/CreateApprovedOrder")
    @Action(input = "http://tempuri.org/IAdminService/CreateApprovedOrder", output = "http://tempuri.org/IAdminService/CreateApprovedOrderResponse")
    @RequestWrapper(localName = "CreateApprovedOrder", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CreateApprovedOrder")
    @ResponseWrapper(localName = "CreateApprovedOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CreateApprovedOrderResponse2")
    @WebResult(name = "CreateApprovedOrderResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.CreateApprovedOrderResponse createApprovedOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.CreateApprovedOrderRequest request
    );

    @WebMethod(operationName = "ChangeInvoiceDueDate", action = "http://tempuri.org/IAdminService/ChangeInvoiceDueDate")
    @Action(input = "http://tempuri.org/IAdminService/ChangeInvoiceDueDate", output = "http://tempuri.org/IAdminService/ChangeInvoiceDueDateResponse")
    @RequestWrapper(localName = "ChangeInvoiceDueDate", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.ChangeInvoiceDueDate")
    @ResponseWrapper(localName = "ChangeInvoiceDueDateResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.ChangeInvoiceDueDateResponse2")
    @WebResult(name = "ChangeInvoiceDueDateResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.ChangeInvoiceDueDateResponse changeInvoiceDueDate(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.ChangeInvoiceDueDateRequest request
    );

    @WebMethod(operationName = "GenerateAccountCreditRegressReport", action = "http://tempuri.org/IAdminService/GenerateAccountCreditRegressReport")
    @Action(input = "http://tempuri.org/IAdminService/GenerateAccountCreditRegressReport", output = "http://tempuri.org/IAdminService/GenerateAccountCreditRegressReportResponse")
    @RequestWrapper(localName = "GenerateAccountCreditRegressReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GenerateAccountCreditRegressReport")
    @ResponseWrapper(localName = "GenerateAccountCreditRegressReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GenerateAccountCreditRegressReportResponse")
    @WebResult(name = "GenerateAccountCreditRegressReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.AccountCreditRegressReportResponse generateAccountCreditRegressReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.AccountCreditRegressReportRequest request
    );

    @WebMethod(operationName = "GetAccountingReport", action = "http://tempuri.org/IAdminService/GetAccountingReport")
    @Action(input = "http://tempuri.org/IAdminService/GetAccountingReport", output = "http://tempuri.org/IAdminService/GetAccountingReportResponse")
    @RequestWrapper(localName = "GetAccountingReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetAccountingReport")
    @ResponseWrapper(localName = "GetAccountingReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetAccountingReportResponse2")
    @WebResult(name = "GetAccountingReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetAccountingReportResponse getAccountingReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetAccountingReportRequest request
    );

    @WebMethod(operationName = "CancelPaymentPlanAmount", action = "http://tempuri.org/IAdminService/CancelPaymentPlanAmount")
    @Action(input = "http://tempuri.org/IAdminService/CancelPaymentPlanAmount", output = "http://tempuri.org/IAdminService/CancelPaymentPlanAmountResponse")
    @RequestWrapper(localName = "CancelPaymentPlanAmount", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelPaymentPlanAmount")
    @ResponseWrapper(localName = "CancelPaymentPlanAmountResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelPaymentPlanAmountResponse2")
    @WebResult(name = "CancelPaymentPlanAmountResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.CancelPaymentPlanAmountResponse cancelPaymentPlanAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.CancelPaymentPlanAmountRequest request
    );

    @WebMethod(operationName = "SearchAccountCredits", action = "http://tempuri.org/IAdminService/SearchAccountCredits")
    @Action(input = "http://tempuri.org/IAdminService/SearchAccountCredits", output = "http://tempuri.org/IAdminService/SearchAccountCreditsResponse")
    @RequestWrapper(localName = "SearchAccountCredits", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.SearchAccountCredits")
    @ResponseWrapper(localName = "SearchAccountCreditsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.SearchAccountCreditsResponse")
    @WebResult(name = "SearchAccountCreditsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.SearchAccountCreditsResponse2 searchAccountCredits(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.SearchAccountCreditsRequest request
    );

    @WebMethod(operationName = "GetFinancialReport", action = "http://tempuri.org/IAdminService/GetFinancialReport")
    @Action(input = "http://tempuri.org/IAdminService/GetFinancialReport", output = "http://tempuri.org/IAdminService/GetFinancialReportResponse")
    @RequestWrapper(localName = "GetFinancialReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetFinancialReport")
    @ResponseWrapper(localName = "GetFinancialReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetFinancialReportResponse2")
    @WebResult(name = "GetFinancialReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetFinancialReportResponse getFinancialReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetFinancialReportRequest request
    );

    @WebMethod(operationName = "GenerateAccountingAgreementType25Report", action = "http://tempuri.org/IAdminService/GenerateAccountingAgreementType25Report")
    @Action(input = "http://tempuri.org/IAdminService/GenerateAccountingAgreementType25Report", output = "http://tempuri.org/IAdminService/GenerateAccountingAgreementType25ReportResponse")
    @RequestWrapper(localName = "GenerateAccountingAgreementType25Report", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GenerateAccountingAgreementType25Report")
    @ResponseWrapper(localName = "GenerateAccountingAgreementType25ReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GenerateAccountingAgreementType25ReportResponse")
    @WebResult(name = "GenerateAccountingAgreementType25ReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.AccountingAgreementType25ReportResponse generateAccountingAgreementType25Report(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.AccountingAgreementType25ReportRequest request
    );

    @WebMethod(operationName = "GetOrderPdfLink", action = "http://tempuri.org/IAdminService/GetOrderPdfLink")
    @Action(input = "http://tempuri.org/IAdminService/GetOrderPdfLink", output = "http://tempuri.org/IAdminService/GetOrderPdfLinkResponse")
    @RequestWrapper(localName = "GetOrderPdfLink", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetOrderPdfLink")
    @ResponseWrapper(localName = "GetOrderPdfLinkResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetOrderPdfLinkResponse")
    @WebResult(name = "GetOrderPdfLinkResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.PdfLinkResponse getOrderPdfLink(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetOrderPdfLinkRequest request
    );

    @WebMethod(operationName = "GetSumOfOrderAmount", action = "http://tempuri.org/IAdminService/GetSumOfOrderAmount")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfOrderAmount", output = "http://tempuri.org/IAdminService/GetSumOfOrderAmountResponse")
    @RequestWrapper(localName = "GetSumOfOrderAmount", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetSumOfOrderAmount")
    @ResponseWrapper(localName = "GetSumOfOrderAmountResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetSumOfOrderAmountResponse")
    @WebResult(name = "GetSumOfOrderAmountResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.SumOfAmountResponse getSumOfOrderAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.SumOfOrderAmountRequest request
    );

    @WebMethod(operationName = "GetInvoiceJournalReport", action = "http://tempuri.org/IAdminService/GetInvoiceJournalReport")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoiceJournalReport", output = "http://tempuri.org/IAdminService/GetInvoiceJournalReportResponse")
    @RequestWrapper(localName = "GetInvoiceJournalReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoiceJournalReport")
    @ResponseWrapper(localName = "GetInvoiceJournalReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoiceJournalReportResponse2")
    @WebResult(name = "GetInvoiceJournalReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetInvoiceJournalReportResponse getInvoiceJournalReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetInvoiceJournalReportRequest request
    );

    @WebMethod(operationName = "GetInvoicePdfLink", action = "http://tempuri.org/IAdminService/GetInvoicePdfLink")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicePdfLink", output = "http://tempuri.org/IAdminService/GetInvoicePdfLinkResponse")
    @RequestWrapper(localName = "GetInvoicePdfLink", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoicePdfLink")
    @ResponseWrapper(localName = "GetInvoicePdfLinkResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoicePdfLinkResponse")
    @WebResult(name = "GetInvoicePdfLinkResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.PdfLinkResponse getInvoicePdfLink(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetInvoicePdfLinkRequest request
    );

    @WebMethod(operationName = "CancelOrderRows", action = "http://tempuri.org/IAdminService/CancelOrderRows")
    @Action(input = "http://tempuri.org/IAdminService/CancelOrderRows", output = "http://tempuri.org/IAdminService/CancelOrderRowsResponse")
    @RequestWrapper(localName = "CancelOrderRows", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelOrderRows")
    @ResponseWrapper(localName = "CancelOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelOrderRowsResponse2")
    @WebResult(name = "CancelOrderRowsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.CancelOrderRowsResponse cancelOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.CancelOrderRowsRequest request
    );

    @WebMethod(operationName = "UpdateOrderRows", action = "http://tempuri.org/IAdminService/UpdateOrderRows")
    @Action(input = "http://tempuri.org/IAdminService/UpdateOrderRows", output = "http://tempuri.org/IAdminService/UpdateOrderRowsResponse")
    @RequestWrapper(localName = "UpdateOrderRows", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.UpdateOrderRows")
    @ResponseWrapper(localName = "UpdateOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.UpdateOrderRowsResponse2")
    @WebResult(name = "UpdateOrderRowsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.UpdateOrderRowsResponse updateOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.UpdateOrderRowsRequest request
    );

    @WebMethod(operationName = "CancelAccountCreditRows", action = "http://tempuri.org/IAdminService/CancelAccountCreditRows")
    @Action(input = "http://tempuri.org/IAdminService/CancelAccountCreditRows", output = "http://tempuri.org/IAdminService/CancelAccountCreditRowsResponse")
    @RequestWrapper(localName = "CancelAccountCreditRows", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelAccountCreditRows")
    @ResponseWrapper(localName = "CancelAccountCreditRowsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelAccountCreditRowsResponse")
    @WebResult(name = "CancelAccountCreditRowsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.CancelAccountCreditRowsResponse2 cancelAccountCreditRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.CancelAccountCreditRowsRequest request
    );

    @WebMethod(operationName = "GetInvoices", action = "http://tempuri.org/IAdminService/GetInvoices")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoices", output = "http://tempuri.org/IAdminService/GetInvoicesResponse")
    @RequestWrapper(localName = "GetInvoices", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoices")
    @ResponseWrapper(localName = "GetInvoicesResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoicesResponse2")
    @WebResult(name = "GetInvoicesResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetInvoicesResponse getInvoices(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetInvoicesRequest request
    );

    @WebMethod(operationName = "CreateOrder", action = "http://tempuri.org/IAdminService/CreateOrder")
    @Action(input = "http://tempuri.org/IAdminService/CreateOrder", output = "http://tempuri.org/IAdminService/CreateOrderResponse")
    @RequestWrapper(localName = "CreateOrder", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CreateOrder")
    @ResponseWrapper(localName = "CreateOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CreateOrderResponse2")
    @WebResult(name = "CreateOrderResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.CreateOrderResponse createOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.CreateOrderRequest request
    );

    @WebMethod(operationName = "GetSumOfPaymentPlanAmount", action = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmount")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmount", output = "http://tempuri.org/IAdminService/GetSumOfPaymentPlanAmountResponse")
    @RequestWrapper(localName = "GetSumOfPaymentPlanAmount", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetSumOfPaymentPlanAmount")
    @ResponseWrapper(localName = "GetSumOfPaymentPlanAmountResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetSumOfPaymentPlanAmountResponse")
    @WebResult(name = "GetSumOfPaymentPlanAmountResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.SumOfAmountResponse getSumOfPaymentPlanAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.SumOfPaymentPlanAmountRequest request
    );

    @WebMethod(operationName = "SearchInvoices", action = "http://tempuri.org/IAdminService/SearchInvoices")
    @Action(input = "http://tempuri.org/IAdminService/SearchInvoices", output = "http://tempuri.org/IAdminService/SearchInvoicesResponse")
    @RequestWrapper(localName = "SearchInvoices", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.SearchInvoices")
    @ResponseWrapper(localName = "SearchInvoicesResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.SearchInvoicesResponse2")
    @WebResult(name = "SearchInvoicesResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.SearchInvoicesResponse searchInvoices(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.SearchInvoicesRequest request
    );

    @WebMethod(operationName = "CancelOrder", action = "http://tempuri.org/IAdminService/CancelOrder")
    @Action(input = "http://tempuri.org/IAdminService/CancelOrder", output = "http://tempuri.org/IAdminService/CancelOrderResponse")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelOrderResponse2")
    @WebResult(name = "CancelOrderResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.CancelOrderResponse cancelOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.CancelOrderRequest request
    );

    @WebMethod(operationName = "CancelAccountCreditAmount", action = "http://tempuri.org/IAdminService/CancelAccountCreditAmount")
    @Action(input = "http://tempuri.org/IAdminService/CancelAccountCreditAmount", output = "http://tempuri.org/IAdminService/CancelAccountCreditAmountResponse")
    @RequestWrapper(localName = "CancelAccountCreditAmount", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelAccountCreditAmount")
    @ResponseWrapper(localName = "CancelAccountCreditAmountResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelAccountCreditAmountResponse")
    @WebResult(name = "CancelAccountCreditAmountResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.CancelAccountCreditAmountResponse2 cancelAccountCreditAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.CancelAccountCreditAmountRequest request
    );

    @WebMethod(operationName = "GetInvoiceReport", action = "http://tempuri.org/IAdminService/GetInvoiceReport")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoiceReport", output = "http://tempuri.org/IAdminService/GetInvoiceReportResponse")
    @RequestWrapper(localName = "GetInvoiceReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoiceReport")
    @ResponseWrapper(localName = "GetInvoiceReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoiceReportResponse2")
    @WebResult(name = "GetInvoiceReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetInvoiceReportResponse getInvoiceReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetInvoiceReportRequest request
    );

    @WebMethod(operationName = "ReleasePendingOrder", action = "http://tempuri.org/IAdminService/ReleasePendingOrder")
    @Action(input = "http://tempuri.org/IAdminService/ReleasePendingOrder", output = "http://tempuri.org/IAdminService/ReleasePendingOrderResponse")
    @RequestWrapper(localName = "ReleasePendingOrder", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.ReleasePendingOrder")
    @ResponseWrapper(localName = "ReleasePendingOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.ReleasePendingOrderResponse")
    @WebResult(name = "ReleasePendingOrderResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.ReleasePendingResponse releasePendingOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.ReleasePendingRequest request
    );

    @WebMethod(operationName = "SearchOrders", action = "http://tempuri.org/IAdminService/SearchOrders")
    @Action(input = "http://tempuri.org/IAdminService/SearchOrders", output = "http://tempuri.org/IAdminService/SearchOrdersResponse")
    @RequestWrapper(localName = "SearchOrders", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.SearchOrders")
    @ResponseWrapper(localName = "SearchOrdersResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.SearchOrdersResponse2")
    @WebResult(name = "SearchOrdersResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.SearchOrdersResponse searchOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.SearchOrdersRequest request
    );

    @WebMethod(operationName = "SearchPaymentPlans", action = "http://tempuri.org/IAdminService/SearchPaymentPlans")
    @Action(input = "http://tempuri.org/IAdminService/SearchPaymentPlans", output = "http://tempuri.org/IAdminService/SearchPaymentPlansResponse")
    @RequestWrapper(localName = "SearchPaymentPlans", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.SearchPaymentPlans")
    @ResponseWrapper(localName = "SearchPaymentPlansResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.SearchPaymentPlansResponse2")
    @WebResult(name = "SearchPaymentPlansResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.SearchPaymentPlansResponse searchPaymentPlans(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.SearchPaymentPlansRequest request
    );

    @WebMethod(operationName = "GetOrderEvents", action = "http://tempuri.org/IAdminService/GetOrderEvents")
    @Action(input = "http://tempuri.org/IAdminService/GetOrderEvents", output = "http://tempuri.org/IAdminService/GetOrderEventsResponse")
    @RequestWrapper(localName = "GetOrderEvents", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetOrderEvents")
    @ResponseWrapper(localName = "GetOrderEventsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetOrderEventsResponse2")
    @WebResult(name = "GetOrderEventsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetOrderEventsResponse getOrderEvents(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetOrderEventsRequest request
    );

    @WebMethod(operationName = "GetDebtInvoicesPaidToClientForReport", action = "http://tempuri.org/IAdminService/GetDebtInvoicesPaidToClientForReport")
    @Action(input = "http://tempuri.org/IAdminService/GetDebtInvoicesPaidToClientForReport", output = "http://tempuri.org/IAdminService/GetDebtInvoicesPaidToClientForReportResponse")
    @RequestWrapper(localName = "GetDebtInvoicesPaidToClientForReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetDebtInvoicesPaidToClientForReport")
    @ResponseWrapper(localName = "GetDebtInvoicesPaidToClientForReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetDebtInvoicesPaidToClientForReportResponse")
    @WebResult(name = "GetDebtInvoicesPaidToClientForReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetDebtInvoicesPaidToClientForReportResponse2 getDebtInvoicesPaidToClientForReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetDebtInvoicesPaidToClientForReportRequest request
    );

    @WebMethod(operationName = "GetKickbackReport", action = "http://tempuri.org/IAdminService/GetKickbackReport")
    @Action(input = "http://tempuri.org/IAdminService/GetKickbackReport", output = "http://tempuri.org/IAdminService/GetKickbackReportResponse")
    @RequestWrapper(localName = "GetKickbackReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetKickbackReport")
    @ResponseWrapper(localName = "GetKickbackReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetKickbackReportResponse")
    @WebResult(name = "GetKickbackReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetKickbackReportResponse2 getKickbackReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetKickbackReportRequest request
    );

    @WebMethod(operationName = "GetAccountCredits", action = "http://tempuri.org/IAdminService/GetAccountCredits")
    @Action(input = "http://tempuri.org/IAdminService/GetAccountCredits", output = "http://tempuri.org/IAdminService/GetAccountCreditsResponse")
    @RequestWrapper(localName = "GetAccountCredits", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetAccountCredits")
    @ResponseWrapper(localName = "GetAccountCreditsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetAccountCreditsResponse")
    @WebResult(name = "GetAccountCreditsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetAccountCreditsResponse2 getAccountCredits(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetAccountCreditsRequest request
    );

    @WebMethod(operationName = "GetClientId", action = "http://tempuri.org/IAdminService/GetClientId")
    @Action(input = "http://tempuri.org/IAdminService/GetClientId", output = "http://tempuri.org/IAdminService/GetClientIdResponse")
    @RequestWrapper(localName = "GetClientId", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetClientId")
    @ResponseWrapper(localName = "GetClientIdResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetClientIdResponse")
    @WebResult(name = "GetClientIdResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetClientIdResponse2 getClientId(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetClientIdRequest request
    );

    @WebMethod(operationName = "CancelPaymentPlanRows", action = "http://tempuri.org/IAdminService/CancelPaymentPlanRows")
    @Action(input = "http://tempuri.org/IAdminService/CancelPaymentPlanRows", output = "http://tempuri.org/IAdminService/CancelPaymentPlanRowsResponse")
    @RequestWrapper(localName = "CancelPaymentPlanRows", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelPaymentPlanRows")
    @ResponseWrapper(localName = "CancelPaymentPlanRowsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CancelPaymentPlanRowsResponse2")
    @WebResult(name = "CancelPaymentPlanRowsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.CancelPaymentPlanRowsResponse cancelPaymentPlanRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.CancelPaymentPlanRowsRequest request
    );

    @WebMethod(operationName = "ApproveInvoice", action = "http://tempuri.org/IAdminService/ApproveInvoice")
    @Action(input = "http://tempuri.org/IAdminService/ApproveInvoice", output = "http://tempuri.org/IAdminService/ApproveInvoiceResponse")
    @RequestWrapper(localName = "ApproveInvoice", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.ApproveInvoice")
    @ResponseWrapper(localName = "ApproveInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.ApproveInvoiceResponse2")
    @WebResult(name = "ApproveInvoiceResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.ApproveInvoiceResponse approveInvoice(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.ApproveInvoiceRequest request
    );

    @WebMethod(operationName = "GetInvoicesWithChangedDueDate", action = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDate")
    @Action(input = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDate", output = "http://tempuri.org/IAdminService/GetInvoicesWithChangedDueDateResponse")
    @RequestWrapper(localName = "GetInvoicesWithChangedDueDate", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoicesWithChangedDueDate")
    @ResponseWrapper(localName = "GetInvoicesWithChangedDueDateResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetInvoicesWithChangedDueDateResponse2")
    @WebResult(name = "GetInvoicesWithChangedDueDateResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetInvoicesWithChangedDueDateResponse getInvoicesWithChangedDueDate(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetInvoicesWithChangedDueDateRequest request
    );

    @WebMethod(operationName = "ExtendOrder", action = "http://tempuri.org/IAdminService/ExtendOrder")
    @Action(input = "http://tempuri.org/IAdminService/ExtendOrder", output = "http://tempuri.org/IAdminService/ExtendOrderResponse")
    @RequestWrapper(localName = "ExtendOrder", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.ExtendOrder")
    @ResponseWrapper(localName = "ExtendOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.ExtendOrderResponse")
    @WebResult(name = "ExtendOrderResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.ExtendOrderResponse2 extendOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.ExtendOrderRequest request
    );

    @WebMethod(operationName = "GetSumOfInvoiceAmount", action = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmount")
    @Action(input = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmount", output = "http://tempuri.org/IAdminService/GetSumOfInvoiceAmountResponse")
    @RequestWrapper(localName = "GetSumOfInvoiceAmount", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetSumOfInvoiceAmount")
    @ResponseWrapper(localName = "GetSumOfInvoiceAmountResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetSumOfInvoiceAmountResponse")
    @WebResult(name = "GetSumOfInvoiceAmountResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.SumOfAmountResponse getSumOfInvoiceAmount(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.SumOfInvoiceAmountRequest request
    );

    @WebMethod(operationName = "AddOrderRows", action = "http://tempuri.org/IAdminService/AddOrderRows")
    @Action(input = "http://tempuri.org/IAdminService/AddOrderRows", output = "http://tempuri.org/IAdminService/AddOrderRowsResponse")
    @RequestWrapper(localName = "AddOrderRows", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.AddOrderRows")
    @ResponseWrapper(localName = "AddOrderRowsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.AddOrderRowsResponse2")
    @WebResult(name = "AddOrderRowsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.AddOrderRowsResponse addOrderRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.AddOrderRowsRequest request
    );

    @WebMethod(operationName = "UpdateOrder", action = "http://tempuri.org/IAdminService/UpdateOrder")
    @Action(input = "http://tempuri.org/IAdminService/UpdateOrder", output = "http://tempuri.org/IAdminService/UpdateOrderResponse")
    @RequestWrapper(localName = "UpdateOrder", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.UpdateOrder")
    @ResponseWrapper(localName = "UpdateOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.UpdateOrderResponse2")
    @WebResult(name = "UpdateOrderResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.UpdateOrderResponse updateOrder(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.UpdateOrderRequest request
    );

    @WebMethod(operationName = "GetRegressionReport", action = "http://tempuri.org/IAdminService/GetRegressionReport")
    @Action(input = "http://tempuri.org/IAdminService/GetRegressionReport", output = "http://tempuri.org/IAdminService/GetRegressionReportResponse")
    @RequestWrapper(localName = "GetRegressionReport", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetRegressionReport")
    @ResponseWrapper(localName = "GetRegressionReportResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetRegressionReportResponse2")
    @WebResult(name = "GetRegressionReportResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetRegressionReportResponse getRegressionReport(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetRegressionReportRequest request
    );

    @WebMethod(operationName = "DeliverOrders", action = "http://tempuri.org/IAdminService/DeliverOrders")
    @Action(input = "http://tempuri.org/IAdminService/DeliverOrders", output = "http://tempuri.org/IAdminService/DeliverOrdersResponse")
    @RequestWrapper(localName = "DeliverOrders", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.DeliverOrders")
    @ResponseWrapper(localName = "DeliverOrdersResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.DeliverOrdersResponse")
    @WebResult(name = "DeliverOrdersResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.DeliveryResponse deliverOrders(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.DeliveryRequest request
    );

    @WebMethod(operationName = "GetPendingReasons", action = "http://tempuri.org/IAdminService/GetPendingReasons")
    @Action(input = "http://tempuri.org/IAdminService/GetPendingReasons", output = "http://tempuri.org/IAdminService/GetPendingReasonsResponse")
    @RequestWrapper(localName = "GetPendingReasons", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetPendingReasons")
    @ResponseWrapper(localName = "GetPendingReasonsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.GetPendingReasonsResponse")
    @WebResult(name = "GetPendingReasonsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.GetPendingReasonsResponse2 getPendingReasons(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.GetPendingReasonsRequest request
    );

    @WebMethod(operationName = "CreditInvoiceRows", action = "http://tempuri.org/IAdminService/CreditInvoiceRows")
    @Action(input = "http://tempuri.org/IAdminService/CreditInvoiceRows", output = "http://tempuri.org/IAdminService/CreditInvoiceRowsResponse")
    @RequestWrapper(localName = "CreditInvoiceRows", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CreditInvoiceRows")
    @ResponseWrapper(localName = "CreditInvoiceRowsResponse", targetNamespace = "http://tempuri.org/", className = "com.svea.webpayadminservice.client.CreditInvoiceRowsResponse")
    @WebResult(name = "CreditInvoiceRowsResult", targetNamespace = "http://tempuri.org/")
    public com.svea.webpayadminservice.client.DeliveryResponse creditInvoiceRows(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.svea.webpayadminservice.client.CreditInvoiceRequest request
    );
}
